### ISSUE TITLE
[KiCad Nightly 5.99] AttributeError: 'module' object has no attribute 'PAD_ATTRIB_STANDARD'

### ISSUE THREAD

**Issue by 0xdec** [openscopeproject/InteractiveHtmlBom#187]
I run into this error when clicking `Generate BOM` in KiCad nightly, and no BOM is generated. The project I'm trying to generate a BOM from is [here](https://gitlab.com/zeroform-design/helmet-communicator/-/tree/master/hardware/bm83-dev-board).

KiCad info:
```
Application: Pcbnew

Version: (5.99.0-3686-g8a382b302), release build

Libraries:
	wxWidgets 3.0.4
	libcurl/7.64.1 SecureTransport (LibreSSL/2.8.3) zlib/1.2.11 nghttp2/1.41.0

Platform: macOS Version 10.16 (Build 20A5384c), 64 bit, Little endian, wxMac

Build Info:
	Date: Sep 30 2020 19:11:48
	wxWidgets: 3.0.4 (wchar_t,STL containers,compatible with 2.8)
	Boost: 1.73.0
	OCC: 7.4.0
	Curl: 7.54.0
	ngspice: 31
	Compiler: Clang 10.0.1 with C++ ABI 1002

Build settings:
	KICAD_SCRIPTING=ON
	KICAD_SCRIPTING_MODULES=ON
	KICAD_SCRIPTING_PYTHON3=OFF
	KICAD_SCRIPTING_WXPYTHON=ON
	KICAD_SCRIPTING_WXPYTHON_PHOENIX=OFF
	KICAD_SCRIPTING_ACTION_MENU=ON
	BUILD_GITHUB_PLUGIN=ON
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```

Exception on python action plugin code:
```
Traceback (most recent call last):

File "/Users/jordi/Library/Preferences/kicad/5.99/scripting/plugins/InteractiveHtmlBom/InteractiveHtmlBom/ecad/kicad.py", line 544, in Run
ibom.run_with_dialog(parser, config, logger)

File "/Users/jordi/Library/Preferences/kicad/5.99/scripting/plugins/InteractiveHtmlBom/InteractiveHtmlBom/core/ibom.py", line 339, in run_with_dialog
main(parser, config, logger)

File "/Users/jordi/Library/Preferences/kicad/5.99/scripting/plugins/InteractiveHtmlBom/InteractiveHtmlBom/core/ibom.py", line 302, in main
pcbdata, components = parser.parse()

File "/Users/jordi/Library/Preferences/kicad/5.99/scripting/plugins/InteractiveHtmlBom/InteractiveHtmlBom/ecad/kicad.py", line 489, in parse
"modules": self.parse_modules(pcb_modules),

File "/Users/jordi/Library/Preferences/kicad/5.99/scripting/plugins/InteractiveHtmlBom/InteractiveHtmlBom/ecad/kicad.py", line 329, in parse_modules
pad_dict = self.parse_pad(p)

File "/Users/jordi/Library/Preferences/kicad/5.99/scripting/plugins/InteractiveHtmlBom/InteractiveHtmlBom/ecad/kicad.py", line 277, in parse_pad
if (pad.GetAttribute() == pcbnew.PAD_ATTRIB_STANDARD or

AttributeError: 'module' object has no attribute 'PAD_ATTRIB_STANDARD'
```

**Comment by 0xdec** [comment]
Traced to [this commit](https://gitlab.com/kicad/code/kicad/-/commit/bf3cb0b1d08335df86f481f3eb6ee28a2c35850e) from 3 days ago
