### ISSUE TITLE
Kicad 5.99, TypeError: ExpandTextVars() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by Plasmabot1** [openscopeproject/InteractiveHtmlBom#221]
Hello, I have this error trying to generate an ibom of a simple board.

Versions:
Windows 10
Kicad nightly 5.99.0-8400-gffdff21f45 (Jan 13 2021)
Latest InteractiveHtmlBom (just copied the `InteractiveHtmlBom` folder into my plugin directory today)

```
Traceback (most recent call last): 

File "C:\Users Anhad\AppData\Roaming\kicad\5....\plugins/InteractiveHtmlBom/ecad/kicad.py", line 631, in Run
ibom.run_with_dialog(parser, config, logger) 

File "C:\Users Anhad\AppData\Roaming\kicad\5....\plugins/InteractiveHtmlBom/core/ibom.py", line 300, in run_with_dialog 
main(parser, config, logger) 

File "C:\Users Anhad\AppData\Roaming\kicad\5....\plugins/InteractiveHtmlBom/core/ibom.py", line 263, in main 
pcbdata, components = parser.parse()

File "C:\Users Anhad\AppData\Roaming\kicad\5....\plugins/InteractiveHtmlBom/core/ibom.py", line 520, in parse 
title = pcbnew.ExpandTextVars(title, project) 

TypeError: ExpandTextVars() takes at least 3 arguments (2 given)
```

Thank you for your help

**Comment by Plasmabot1** [comment]
Update:
I downloaded the latest KiCAD nightly and the issue no longer occurs.
