### ISSUE TITLE
Python 3.9 compatibility

### ISSUE THREAD

**Issue by Craftplorer** [openscopeproject/InteractiveHtmlBom#245]
I got following error when using python 3.9 importing an eagle file.
Seems to be a similar issue as #233 

```
Traceback (most recent call last):
  File "C:\Users\User\Documents\eagle\InteractiveHtmlBom\generate_interactive_bom.py", line 52, in <module>
    ibom.main(parser, config, logger)
  File "C:\Users\User\Documents\eagle\InteractiveHtmlBom\core\ibom.py", line 293, in main
    pcbdata, components = parser.parse()
  File "C:\Users\User\Documents\eagle\InteractiveHtmlBom\ecad\easyeda.py", line 427, in parse
    pcb = self.get_easyeda_pcb()
  File "C:\Users\User\Documents\eagle\InteractiveHtmlBom\ecad\easyeda.py", line 28, in get_easyeda_pcb
    return json.load(f, encoding='utf-8')
  File "C:\Users\User\scoop\apps\python\current\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\User\scoop\apps\python\current\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

**Comment by Craftplorer** [comment]
Seems already fixed on master

**Comment by Craftplorer** [comment]
Seems already fixed on master
