### ISSUE TITLE
"No PointCount method on outline object"

### ISSUE THREAD

**Issue by jbtronics** [openscopeproject/InteractiveHtmlBom#26]
When i try to apply HtmlBOM on this PCB
[Mainboard.zip](https://github.com/openscopeproject/InteractiveHtmlBom/files/2262828/Mainboard.zip), the error message "No PointCount method on outline object. Unpatched kicad version?" occurs.

Im using KiCad 5.0.0 (but this PCB was originally created on an older 5RC version). All other PCBs in my project can be used for generating a BOM using your script, only this one does not work.

The stack trace says:
``` plugin.Run()

No PointCount method on outline object. Unpatched kicad version?
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\user\AppData\Roaming\kicad\scripting/InteractiveHtmlBom/generate_interactive_bom.py", line 446, in Run
    main(pcbnew.GetBoard())
  File "C:\Users\user\AppData\Roaming\kicad\scripting/InteractiveHtmlBom/generate_interactive_bom.py", line 402, in main
    "silkscreen": parse_silkscreen(pcb),
  File "C:\Users\user\AppData\Roaming\kicad\scripting/InteractiveHtmlBom/generate_interactive_bom.py", line 236, in parse_silkscreen
    drawing = parse_drawing(d)
  File "C:\Users\user\AppData\Roaming\kicad\scripting/InteractiveHtmlBom/generate_interactive_bom.py", line 206, in parse_drawing
    return parse_draw_segment(d)
  File "C:\Users\user\AppData\Roaming\kicad\scripting/InteractiveHtmlBom/generate_interactive_bom.py", line 154, in parse_draw_segment
    "angle": d.GetParentModule().GetOrientation() * 0.1,
AttributeError: 'NoneType' object has no attribute 'GetOrientation''```

**Comment by qu1ck** [comment]
I think I caught it. If you still have issues please reopen this bug.
