### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by ankithjv** [openscopeproject/InteractiveHtmlBom#394]
2023-06-07 11:14:29,962 ERROR File Z:\3U_gang_relay_rev_A1.json does not comply with json schema. {'type': 'segment', 'start': [4440.0, -3935.0], 'end': [4010.0, -3935.0], 'width': 0.0} is valid under each of {'$ref': '#/definitions/DrawingRect'}, {'$ref': '#/definitions/DrawingSegment'}
Traceback (most recent call last):
  File "Z:\Git\InteractiveHtmlBom\InteractiveHtmlBom\generate_interactive_bom.py", line 84, in <module>
    main()
  File "Z:\Git\InteractiveHtmlBom\InteractiveHtmlBom\generate_interactive_bom.py", line 77, in main
    ibom.main(parser, config, logger)
  File "Z:\Git\InteractiveHtmlBom\InteractiveHtmlBom\core\ibom.py", line 322, in main
    pcbdata, components = parser.parse()
  File "Z:\Git\InteractiveHtmlBom\InteractiveHtmlBom\ecad\genericjson.py", line 148, in parse
    for drawing in pcbdata['edges']:
TypeError: 'NoneType' object is not subscriptable

**Comment by qu1ck** [comment]
Please don't multiply issues for no good reason, lets continue in the other one that has more context.
