### ISSUE TITLE
Support for padstacks (from kicad nightly)

### ISSUE THREAD

**Issue by arturo182** [openscopeproject/InteractiveHtmlBom#471]
KiCad Version: 8.99.0-2584-g661ed81e6f, release build
Plugin: latest master (5915a24)

```python
Traceback (most recent call last):

  File "E:\Documents\KiCad\8.99\3rdparty\plugins\org_openscopeproject_InteractiveHtmlBom\ecad\kicad.py", line 864, in Run
    ibom.run_with_dialog(parser, config, logger)

  File "E:\Documents\KiCad\8.99\3rdparty\plugins\org_openscopeproject_InteractiveHtmlBom\core\ibom.py", line 363, in run_with_dialog
    main(parser, config, logger)

  File "E:\Documents\KiCad\8.99\3rdparty\plugins\org_openscopeproject_InteractiveHtmlBom\core\ibom.py", line 327, in main
    pcbdata, components = parser.parse()
                          ^^^^^^^^^^^^^^

  File "E:\Documents\KiCad\8.99\3rdparty\plugins\org_openscopeproject_InteractiveHtmlBom\ecad\kicad.py", line 781, in parse
    "footprints": self.parse_footprints(),
                  ^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Documents\KiCad\8.99\3rdparty\plugins\org_openscopeproject_InteractiveHtmlBom\ecad\kicad.py", line 564, in parse_footprints
    pad_dict = self.parse_pad(p)
               ^^^^^^^^^^^^^^^^^

  File "E:\Documents\KiCad\8.99\3rdparty\plugins\org_openscopeproject_InteractiveHtmlBom\ecad\kicad.py", line 490, in parse_pad
    pad_dict["radius"] = pad.GetRoundRectCornerRadius() * 1e-6
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: PAD.GetRoundRectCornerRadius() missing 1 required positional argument: 'aLayer'
```

Fixed locally by changing:
```diff
--- a/ecad/kicad.py
+++ b/ecad/kicad.py
@@ -487,7 +487,7 @@ class PcbnewParser(EcadParser):
             ]]

         if shape in ["roundrect", "chamfrect"]:
-            pad_dict["radius"] = pad.GetRoundRectCornerRadius() * 1e-6
+            pad_dict["radius"] = pad.GetRoundRectCornerRadius(layers_set[0]) * 1e-6
         if shape == "chamfrect":
             pad_dict["chamfpos"] = pad.GetChamferPositions()
             pad_dict["chamfratio"] = pad.GetChamferRectRatio()
```

But not sure if that's the right way to do it.

**Comment by qu1ck** [comment]
It's a decent workaround for now but proper fix needs padstack support. But kicad's own implementation is not yet complete so I'll wait on this.

**Comment by Bowlsnapper** [comment]
Yeah, I have the same issue. Definitely a bummer, but I hope a fix can be found! :)

**Comment by qu1ck** [comment]
You need to reload kicad after you change the plugin (or do plugin refresh from the pcbnew menu). If you still have an issue it should not be exact same one, show me your error message.

**Comment by Bowlsnapper** [comment]
![htmlbomerror](https://github.com/user-attachments/assets/c236a031-bfb9-4d19-baeb-67478a8a934d)

**Comment by qu1ck** [comment]
I suspect your nightly is old, I fixed that on kicad side a while ago.

**Comment by Bowlsnapper** [comment]
Hmmm, lemmie update and see.

**Comment by Bowlsnapper** [comment]
Yes, you are correct. Installing the latest nightly fixed the issue. You are a god. I love your work.

**Comment by robomechs** [comment]
for me it didn't  help.
Application: KiCad x64 on x64
Version: 8.99.0-2659-gf7f86174a0, release build
<img width="592" alt="Screenshot" src="https://github.com/user-attachments/assets/0a99c457-17d6-4381-885c-146b1747ec28">

**Comment by robomechs** [comment]
> Yes, you are correct. Installing the latest nightly fixed the issue. You are a god. I love your work.

Which version have you used for success?

**Comment by qu1ck** [comment]
You either did not apply the modification correctly or did not reload the plugin or restart kicad. Your screenshot shows current code, not modified one.

**Comment by robomechs** [comment]
Seems like I didn't apply modification correctly, becayse I installed last KiCad version and reload the computer just in case.

**Comment by robomechs** [comment]
from box I've got this error:
![image](https://github.com/user-attachments/assets/2a713e21-6479-4185-b46e-32b2528e1bdb)
arter that I download last ibom from github and put it instead of the one from "box", reload KiCad, and
<img width="592" alt="Screenshot" src="https://github.com/user-attachments/assets/f4447177-c16b-4634-8b71-1082e6cef11c">

**Comment by qu1ck** [comment]
Yeah and to fix that last error you need to change the code like the first post shows.
Change this line in `kicad.py`
`pad_dict["radius"] = pad.GetRoundRectCornerRadius() * 1e-6`
to
`pad_dict["radius"] = pad.GetRoundRectCornerRadius(layers_set[0]) * 1e-6`
