### ISSUE TITLE
TypeError: FOOTPRINT_GetBoundingBox expected at most 2 arguments, got 3

### ISSUE THREAD

**Issue by omerk** [openscopeproject/InteractiveHtmlBom#476]
Hi,

Using the latest nightly (`kicad-nightly-8.99.0.2837.g1dfe431c00`), and current `main` (5915a24), ibom fails with error: `TypeError: FOOTPRINT_GetBoundingBox expected at most 2 arguments, got 3`.

The full error message:
```
---------------------------
Exception on python action plugin code
---------------------------
Traceback (most recent call last):

  File "C:\Users\omerk\Documents\KiCad\8.99\3rdparty\plugins\org_openscopeproject_InteractiveHtmlBom\ecad\kicad.py", line 841, in Run
    self.icon_file_name = os.path.join(icon_dir, 'icon.png')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\omerk\Documents\KiCad\8.99\3rdparty\plugins\org_openscopeproject_InteractiveHtmlBom\core\ibom.py", line 363, in run_with_dialog
    main(parser, config, logger)

  File "C:\Users\omerk\Documents\KiCad\8.99\3rdparty\plugins\org_openscopeproject_InteractiveHtmlBom\core\ibom.py", line 327, in main
    pcbdata, components = parser.parse()
                          ^^^^^^^^^^^^^^

  File "C:\Users\omerk\Documents\KiCad\8.99\3rdparty\plugins\org_openscopeproject_InteractiveHtmlBom\ecad\kicad.py", line 758, in parse
    if bbox is None:
                     

  File "C:\Users\omerk\Documents\KiCad\8.99\3rdparty\plugins\org_openscopeproject_InteractiveHtmlBom\ecad\kicad.py", line 519, in parse_footprints
    for f in self.footprints:
                             ^

  File "C:\Program Files\KiCad\8.99\bin\Lib\site-packages\pcbnew.py", line 19937, in GetBoundingBox
    return _pcbnew.FOOTPRINT_GetBoundingBox(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: FOOTPRINT_GetBoundingBox expected at most 2 arguments, got 3
Additional information:
Wrong number or type of arguments for overloaded function 'FOOTPRINT_GetBoundingBox'.
  Possible C/C++ prototypes are:
    FOOTPRINT::GetBoundingBox() const
    FOOTPRINT::GetBoundingBox(bool) const
```

Looking at other issues, it looks there might some interface changes that are not finalised in Kicad that the plugin might not support yet? Wondering if there's a workaround for now that we can use while those changes are ironed out?

Thanks for your assistance and your continued work on one of the greatest productivity boosters in the EDA space!

**Comment by omerk** [comment]
Not entirely sure what happened there but it's entirely possible that I may not have restarted KiCAD after overwriting the plugins folder with a zipball from Github. I think I just assumed that if I closed the PCB editor it would be okay, but evidently not.

Upon restarting KiCAD, and running the plugin, I got:

`TypeError: PAD.GetRoundRectCornerRadius() missing 1 required positional argument: 'aLayer'`

Which, after applying the workaround in https://github.com/openscopeproject/InteractiveHtmlBom/issues/471#issue-2583018022 disappeared.

All working now, thanks for your help!
